name: Deploy Github Pages 
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: npm install --legacy-peer-deps && npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: madlogos/vueresume
          branch: gh-pages
          folder: dist